# Generated by Django 4.0.3 on 2022-03-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truQ_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
