# Generated by Django 4.0.3 on 2022-03-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truQ_auth', '0002_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
